=== npdev/backend-js-coding-test-main/data/schemas/companies.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "industry": {
          "type": "string"
        },
        "active": {
          "type": "boolean"
        },
        "website": {
          "type": "string",
          "format": "uri"
        },
        "telephone": {
          "type": "string",
          "pattern": "^[0-9-]+$"
        },
        "slogan": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": ["id", "name", "industry", "active", "website", "telephone", "slogan", "address", "city", "country"],
      "additionalProperties": false
    }
  }

=== npdev/backend-js-coding-test-main/data/companies/aac1259dfa2c6c5ead508f34e52bb990.json
[{"id":1,"name":"Ondricka and Sons","industry":"n/a","active":false,"website":"https://twitpic.com","telephone":"626-135-8533","slogan":"Universal bandwidth-monitored orchestration","address":"71 Emmet Avenue","city":"Pasadena","country":"United States"},
{"id":2,"name":"Gusikowski, Cassin and Hagenes","industry":"Major Banks","active":false,"website":"http://google.nl","telephone":"858-157-2878","slogan":"Visionary dynamic infrastructure","address":"5053 Northland Circle","city":"San Diego","country":"United States"},
{"id":3,"name":"Osinski, Zulauf and Beier","industry":"Real Estate Investment Trusts","active":true,"website":"https://uol.com.br","telephone":"407-924-5777","slogan":"Networked national hub","address":"0 Kinsman Circle","city":"Kissimmee","country":"United States"},
{"id":4,"name":"Runolfsson LLC","industry":"Package Goods/Cosmetics","active":true,"website":"https://miitbeian.gov.cn","telephone":"616-430-4560","slogan":"Upgradable explicit parallelism","address":"9 Forster Crossing","city":"Grand Rapids","country":"United States"},
{"id":5,"name":"Mosciski LLC","industry":"Real Estate Investment Trusts","active":false,"website":"https://de.vu","telephone":"305-318-1615","slogan":"Ameliorated dedicated circuit","address":"68 Oxford Circle","city":"Clearwater","country":"United States"},
{"id":6,"name":"Howe-Zboncak","industry":"Major Banks","active":false,"website":"http://accuweather.com","telephone":"611-768-4603","slogan":"Object-based optimizing initiative","address":"297 Dixon Lane","city":"Greater Napanee","country":"Canada"},
{"id":7,"name":"Kihn Inc","industry":"n/a","active":false,"website":"https://dailymail.co.uk","telephone":"303-598-4045","slogan":"Persistent foreground budgetary management","address":"779 West Pass","city":"Boulder","country":"United States"},
{"id":8,"name":"Effertz-Wolf","industry":"Computer Software: Programming, Data Processing","active":true,"website":"https://toplist.cz","telephone":"757-815-4826","slogan":"Monitored bandwidth-monitored encoding","address":"52687 Hovde Junction","city":"Chesapeake","country":"United States"},
{"id":9,"name":"Howe and Sons","industry":"Major Pharmaceuticals","active":false,"website":"https://mozilla.com","telephone":"981-800-8161","slogan":"Centralized bifurcated database","address":"724 Loomis Hill","city":"Blainville","country":"Canada"},
{"id":10,"name":"Bosco LLC","industry":"Major Pharmaceuticals","active":true,"website":"http://hao123.com","telephone":"924-994-0064","slogan":"Compatible human-resource capability","address":"52 Blue Bill Park Point","city":"Lions Bay","country":"Canada"},
{"id":11,"name":"Bayer and Sons","industry":"Real Estate Investment Trusts","active":true,"website":"http://unblog.fr","telephone":"187-321-4674","slogan":"Multi-channelled systematic policy","address":"574 Monterey Place","city":"Swift Current","country":"Canada"},
{"id":12,"name":"Fay-Pagac","industry":"Major Pharmaceuticals","active":true,"website":"https://exblog.jp","telephone":"402-653-7286","slogan":"Devolved secondary synergy","address":"96512 Milwaukee Trail","city":"Saskatoon","country":"Canada"},
{"id":13,"name":"Bergnaum, Wintheiser and Halvorson","industry":"Natural Gas Distribution","active":true,"website":"https://dailymail.co.uk","telephone":"316-935-8723","slogan":"Programmable discrete focus group","address":"223 Briar Crest Place","city":"Wichita","country":"United States"},
{"id":14,"name":"Friesen-Torp","industry":"Major Pharmaceuticals","active":false,"website":"http://rakuten.co.jp","telephone":"337-136-3450","slogan":"Configurable even-keeled customer loyalty","address":"7 John Wall Street","city":"Lafayette","country":"United States"},
{"id":15,"name":"Abernathy, Block and Kuhlman","industry":"Precious Metals","active":true,"website":"https://mapy.cz","telephone":"304-297-7591","slogan":"Sharable neutral capability","address":"5203 Barby Terrace","city":"Charleston","country":"United States"},
{"id":16,"name":"Bashirian, Hyatt and Hayes","industry":"EDP Services","active":false,"website":"https://umn.edu","telephone":"409-104-1651","slogan":"Secured cohesive utilisation","address":"12 Jay Alley","city":"Beaumont","country":"United States"},
{"id":17,"name":"Daniel, Roob and Reynolds","industry":"Biotechnology: In Vitro & In Vivo Diagnostic Substances","active":true,"website":"https://state.gov","telephone":"305-413-2995","slogan":"Automated asynchronous secured line","address":"2 Buell Junction","city":"Miami Beach","country":"United States"},
{"id":18,"name":"Brekke, Hackett and Wisozk","industry":"n/a","active":true,"website":"http://wix.com","telephone":"202-206-2827","slogan":"Focused local time-frame","address":"590 Vahlen Hill","city":"Washington","country":"United States"},
{"id":19,"name":"Ledner LLC","industry":"n/a","active":true,"website":"https://godaddy.com","telephone":"857-562-8396","slogan":"Function-based needs-based protocol","address":"2087 Pearson Pass","city":"Boston","country":"United States"},
{"id":20,"name":"Yundt, Kirlin and Jaskolski","industry":"Computer Software: Programming, Data Processing","active":false,"website":"https://ucoz.com","telephone":"757-740-1457","slogan":"Multi-channelled dynamic structure","address":"035 Kipling Crossing","city":"Virginia Beach","country":"United States"},
{"id":21,"name":"O'Conner-Hickle","industry":"n/a","active":false,"website":"https://macromedia.com","telephone":"302-730-2760","slogan":"Inverse eco-centric encryption","address":"1546 Debs Way","city":"Newark","country":"United States"},
{"id":22,"name":"Reynolds, Wiza and Schneider","industry":"n/a","active":false,"website":"http://salon.com","telephone":"915-107-2321","slogan":"Proactive fresh-thinking data-warehouse","address":"27 Bluestem Trail","city":"El Paso","country":"United States"},
{"id":23,"name":"Johns, Wunsch and Labadie","industry":"Electrical Products","active":true,"website":"https://vimeo.com","telephone":"407-333-1491","slogan":"Reverse-engineered discrete structure","address":"9861 Riverside Alley","city":"Orlando","country":"United States"},
{"id":24,"name":"Schowalter, Bashirian and Rowe","industry":"Finance: Consumer Services","active":true,"website":"http://t.co","telephone":"936-195-4981","slogan":"Extended optimal success","address":"69 Melrose Avenue","city":"Penticton","country":"Canada"},
{"id":25,"name":"Gorczany, Dibbert and Goodwin","industry":"Specialty Insurers","active":false,"website":"https://google.nl","telephone":"916-508-0891","slogan":"Upgradable even-keeled model","address":"3946 Ryan Court","city":"Sacramento","country":"United States"}]

=== npdev/backend-js-coding-test-main/data/companies/0cc175b9c0f1b6a831c399e269772661.json
[{"id":26,"name":"Bode and Sons","industry":"Other Consumer Services","active":true,"website":"https://devhub.com","telephone":"304-534-5956","slogan":"Monitored system-worthy pricing structure","address":"5 Atwood Road","city":"Charleston","country":"United States"},
{"id":27,"name":"Murphy-Witting","industry":"Packaged Foods","active":false,"website":"http://purevolume.com","telephone":"301-578-5980","slogan":"Advanced fault-tolerant initiative","address":"67 Hanson Court","city":"Hyattsville","country":"United States"},
{"id":28,"name":"Ondricka, Volkman and Berge","industry":"Marine Transportation","active":true,"website":"http://google.fr","telephone":"301-949-6857","slogan":"Innovative transitional process improvement","address":"6502 Barnett Point","city":"Hyattsville","country":"United States"},
{"id":29,"name":"Jenkins-Romaguera","industry":"Savings Institutions","active":false,"website":"http://e-recht24.de","telephone":"212-474-3727","slogan":"Cloned executive interface","address":"234 Twin Pines Point","city":"Miramichi","country":"Canada"},
{"id":30,"name":"Ward-Blanda","industry":"n/a","active":true,"website":"https://seattletimes.com","telephone":"417-449-7373","slogan":"Right-sized actuating hub","address":"12191 Montana Alley","city":"Springfield","country":"United States"},
{"id":31,"name":"Simonis LLC","industry":"Finance: Consumer Services","active":true,"website":"http://mlb.com","telephone":"254-326-5067","slogan":"Visionary leading edge artificial intelligence","address":"68649 Cascade Place","city":"Waco","country":"United States"},
{"id":32,"name":"Nicolas, Lockman and Keeling","industry":"n/a","active":true,"website":"http://pagesperso-orange.fr","telephone":"480-204-7726","slogan":"Automated disintermediate access","address":"2 Weeping Birch Junction","city":"Tempe","country":"United States"},
{"id":33,"name":"McClure-McCullough","industry":"Major Banks","active":false,"website":"http://flickr.com","telephone":"325-234-1724","slogan":"User-friendly radical internet solution","address":"4 Cherokee Hill","city":"San Angelo","country":"United States"},
{"id":34,"name":"Stanton, O'Reilly and Streich","industry":"Containers/Packaging","active":true,"website":"https://army.mil","telephone":"827-652-0885","slogan":"Self-enabling asynchronous structure","address":"75 Badeau Lane","city":"Keswick","country":"Canada"}]

=== npdev/backend-js-coding-test-main/data/companies/6c1d77a1851c78aa2894f8b7be3f7af4.json
[{"id":72,"name":"Lakin, Upton and Emard","industry":"n/a","active":true,"website":"http://histats.com","telephone":"918-436-1656","slogan":"Mandatory client-driven frame","address":"2010 Veith Alley","city":"Tulsa","country":"United States"},
{"id":73,"name":"Murazik and Sons","industry":"Property-Casualty Insurers","active":false,"website":"http://bloglovin.com","telephone":"336-591-8382","slogan":"Assimilated well-modulated approach","address":"3917 Express Center","city":"Winston Salem","country":"United States"},
{"id":74,"name":"Purdy, Koepp and Zboncak","industry":"Department/Specialty Retail Stores","active":true,"website":"https://redcross.org","telephone":"352-748-5551","slogan":"Phased demand-driven functionalities","address":"2502 Ryan Hill","city":"Gainesville","country":"United States"},
{"id":75,"name":"Kunze Group","industry":"Oil & Gas Production","active":true,"website":"https://virginia.edu","telephone":"841-440-6095","slogan":"Vision-oriented mission-critical capacity","address":"15 Forest Run Court","city":"Cochrane","country":"Canada"},
{"id":76,"name":"Carter LLC","industry":"n/a","active":false,"website":"https://gizmodo.com","telephone":"937-443-7729","slogan":"Cross-group analyzing core","address":"675 Cambridge Court","city":"Dayton","country":"United States"},
{"id":77,"name":"Monahan, Hintz and Kunze","industry":"Property-Casualty Insurers","active":false,"website":"https://edublogs.org","telephone":"589-359-2617","slogan":"Fundamental bifurcated moderator","address":"558 Carioca Hill","city":"Sainte-Anne-des-Monts","country":"Canada"},
{"id":78,"name":"Kub, Hoppe and Dach","industry":"Real Estate","active":false,"website":"http://rambler.ru","telephone":"792-250-9413","slogan":"Synchronised scalable groupware","address":"101 Di Loreto Junction","city":"Dieppe","country":"Canada"},
{"id":79,"name":"Hessel Group","industry":"n/a","active":true,"website":"http://buzzfeed.com","telephone":"540-111-9690","slogan":"Automated asynchronous application","address":"090 Troy Way","city":"Roanoke","country":"United States"},
{"id":80,"name":"Collins and Sons","industry":"Hotels/Resorts","active":false,"website":"http://yelp.com","telephone":"303-424-8972","slogan":"Triple-buffered executive collaboration","address":"31 Buhler Terrace","city":"Denver","country":"United States"},
{"id":81,"name":"Rempel, Dicki and Graham","industry":"EDP Services","active":false,"website":"https://shop-pro.jp","telephone":"204-296-9293","slogan":"Ergonomic coherent conglomeration","address":"9046 Dahle Point","city":"Mascouche","country":"Canada"},
{"id":82,"name":"Hodkiewicz LLC","industry":"Real Estate Investment Trusts","active":false,"website":"http://godaddy.com","telephone":"232-784-6056","slogan":"Public-key directional array","address":"0016 Twin Pines Drive","city":"Aylmer","country":"Canada"},
{"id":83,"name":"Wolf-Gislason","industry":"n/a","active":false,"website":"https://hubpages.com","telephone":"125-897-3984","slogan":"Virtual fresh-thinking matrices","address":"7484 Burning Wood Court","city":"Waitara","country":"New Zealand"},
{"id":84,"name":"Little, Abernathy and Marvin","industry":"n/a","active":true,"website":"http://wiley.com","telephone":"645-724-1733","slogan":"Front-line scalable database","address":"5 Drewry Lane","city":"Brisbane","country":"Australia"},
{"id":85,"name":"Satterfield, Tillman and Zboncak","industry":"Marine Transportation","active":true,"website":"https://marketwatch.com","telephone":"399-229-6601","slogan":"Optional static implementation","address":"877 Wayridge Circle","city":"Sarnia","country":"Canada"},
{"id":86,"name":"Dibbert, Ernser and Schmeler","industry":"n/a","active":true,"website":"http://stanford.edu","telephone":"316-647-0578","slogan":"Fundamental leading edge definition","address":"7667 Mendota Hill","city":"Wichita","country":"United States"},
{"id":87,"name":"Schmeler, Jacobs and Tromp","industry":"n/a","active":true,"website":"http://surveymonkey.com","telephone":"971-122-8321","slogan":"Right-sized 5th generation info-mediaries","address":"01 Tennyson Junction","city":"Portland","country":"United States"},
{"id":88,"name":"Spinka, Boehm and Osinski","industry":"Restaurants","active":false,"website":"https://angelfire.com","telephone":"913-872-2823","slogan":"Optimized zero defect secured line","address":"619 Farmco Place","city":"Delaware","country":"Canada"},
{"id":89,"name":"Langworth-Johnson","industry":"Specialty Chemicals","active":false,"website":"https://mozilla.org","telephone":"773-196-9862","slogan":"Decentralized neutral project","address":"7 Badeau Court","city":"Chicago","country":"United States"},
{"id":90,"name":"Fay, Hoppe and Goodwin","industry":"Natural Gas Distribution","active":true,"website":"http://eepurl.com","telephone":"323-745-1776","slogan":"Up-sized cohesive knowledge base","address":"2992 Clemons Center","city":"Los Angeles","country":"United States"},
{"id":91,"name":"Johns Inc","industry":"n/a","active":true,"website":"https://newsvine.com","telephone":"414-203-3203","slogan":"Balanced even-keeled extranet","address":"703 Portage Plaza","city":"Milwaukee","country":"United States"},
{"id":92,"name":"Rodriguez, Skiles and Predovic","industry":"n/a","active":true,"website":"https://surveymonkey.com","telephone":"760-324-1444","slogan":"Virtual optimizing function","address":"579 American Road","city":"Huntington Beach","country":"United States"},
{"id":93,"name":"Lowe, Bosco and Huels","industry":"Commercial Banks","active":true,"website":"https://marketwatch.com","telephone":"754-274-4874","slogan":"Focused clear-thinking definition","address":"6932 Prairieview Road","city":"Fort Lauderdale","country":"United States"},
{"id":94,"name":"Grady LLC","industry":"Home Furnishings","active":false,"website":"https://theguardian.com","telephone":"678-377-7740","slogan":"Operative eco-centric initiative","address":"3 West Way","city":"Raymond","country":"Canada"},
{"id":95,"name":"Grant-Anderson","industry":"n/a","active":false,"website":"https://com.com","telephone":"318-661-8576","slogan":"Down-sized non-volatile internet solution","address":"9460 Barnett Park","city":"Shreveport","country":"United States"},
{"id":96,"name":"Pacocha and Sons","industry":"Forest Products","active":false,"website":"http://technorati.com","telephone":"215-556-0856","slogan":"Automated full-range migration","address":"82 Stephen Plaza","city":"Philadelphia","country":"United States"},
{"id":97,"name":"Emmerich-Nicolas","industry":"Major Banks","active":false,"website":"http://weibo.com","telephone":"387-152-1473","slogan":"Programmable static process improvement","address":"5583 Hauk Way","city":"Waihi","country":"New Zealand"},
{"id":98,"name":"Collier-Roberts","industry":"Containers/Packaging","active":false,"website":"https://opensource.org","telephone":"100-799-8031","slogan":"Balanced empowering approach","address":"30594 Mendota Parkway","city":"Prince Edward","country":"Canada"},
{"id":99,"name":"Kertzmann-Miller","industry":"Major Pharmaceuticals","active":true,"website":"https://youtube.com","telephone":"962-756-2238","slogan":"Synchronised foreground encoding","address":"94405 Ridgeway Street","city":"Richmond","country":"New Zealand"},
{"id":100,"name":"Schiller, Moore and Stark","industry":"Multi-Sector Companies","active":true,"website":"http://reverbnation.com","telephone":"617-883-4147","slogan":"Ameliorated coherent function","address":"14825 Elka Avenue","city":"Boston","country":"United States"}]

=== npdev/backend-js-coding-test-main/__tests__/test_data/companies.json
[{"id":26,"name":"Bode and Sons","industry":"Other Consumer Services","active":true,"website":"https://devhub.com","telephone":"304-534-5956","slogan":"Monitored system-worthy pricing structure","address":"5 Atwood Road","city":"Charleston","country":"United States"},
{"id":27,"name":"Murphy-Witting","industry":"Packaged Foods","active":false,"website":"http://purevolume.com","telephone":"301-578-5980","slogan":"Advanced fault-tolerant initiative","address":"67 Hanson Court","city":"Hyattsville","country":"United States"}]

=== npdev/backend-js-coding-test-main/data/companies/051b3fc9c5aa2303f1040c53cb8473cc.json
[{"id":35,"name":"Moen-Harber","industry":"Major Banks","active":false,"website":"http://live.com","telephone":"704-344-3368","slogan":"Object-based uniform monitoring","address":"5663 Pawling Park","city":"Charlotte","country":"United States"},
{"id":36,"name":"Pouros, Murphy and Vandervort","industry":"Major Chemicals","active":false,"website":"http://cdbaby.com","telephone":"702-618-0399","slogan":"Devolved bandwidth-monitored solution","address":"04333 Fuller Park","city":"Saint-Bruno-de-Montarville","country":"Canada"},
{"id":37,"name":"Crooks-Russel","industry":"Major Banks","active":false,"website":"https://nps.gov","telephone":"202-131-9615","slogan":"Grass-roots secondary contingency","address":"52532 Parkside Circle","city":"Washington","country":"United States"},
{"id":38,"name":"Schumm, Kohler and Yundt","industry":"Oil & Gas Production","active":false,"website":"http://spiegel.de","telephone":"570-272-9649","slogan":"Fundamental eco-centric extranet","address":"1 Mccormick Trail","city":"Scranton","country":"United States"},
{"id":39,"name":"Satterfield-MacGyver","industry":"Oil & Gas Production","active":true,"website":"https://gmpg.org","telephone":"512-453-3403","slogan":"Managed radical approach","address":"12112 Express Alley","city":"Austin","country":"United States"},
{"id":40,"name":"Stokes, Dooley and Muller","industry":"Industrial Machinery/Components","active":false,"website":"http://paypal.com","telephone":"816-227-7107","slogan":"Sharable modular policy","address":"127 Magdeline Place","city":"Kansas City","country":"United States"},
{"id":41,"name":"Terry LLC","industry":"Telecommunications Equipment","active":true,"website":"http://clickbank.net","telephone":"529-130-7939","slogan":"Customer-focused dynamic algorithm","address":"8 Mendota Trail","city":"Virden","country":"Canada"},
{"id":42,"name":"Weber, Gislason and Huel","industry":"Commercial Banks","active":true,"website":"http://berkeley.edu","telephone":"470-408-7066","slogan":"Front-line even-keeled local area network","address":"6122 Mcguire Road","city":"Sarnia","country":"Canada"},
{"id":43,"name":"Rosenbaum Inc","industry":"Savings Institutions","active":true,"website":"http://cornell.edu","telephone":"719-887-9989","slogan":"Automated regional core","address":"585 Green Road","city":"Colorado Springs","country":"United States"},
{"id":44,"name":"Pacocha-Lowe","industry":"Major Banks","active":true,"website":"http://usda.gov","telephone":"812-947-8340","slogan":"Team-oriented explicit ability","address":"95 Anthes Alley","city":"Bloomington","country":"United States"},
{"id":45,"name":"Schmitt-Blick","industry":"n/a","active":true,"website":"https://blogs.com","telephone":"-305-5106","slogan":"Switchable high-level local area network","address":"37002 Scoville Drive","city":"Pittsburgh","country":"United States"},
{"id":46,"name":"Koelpin-Wuckert","industry":"Food Distributors","active":true,"website":"https://storify.com","telephone":"714-360-8144","slogan":"Pre-emptive motivating product","address":"216 Texas Plaza","city":"Fullerton","country":"United States"},
{"id":47,"name":"Nitzsche, Monahan and Cartwright","industry":"Biotechnology: Laboratory Analytical Instruments","active":false,"website":"https://technorati.com","telephone":"804-874-6804","slogan":"Optional holistic capability","address":"551 Corben Plaza","city":"Fermont","country":"Canada"},
{"id":48,"name":"Tremblay-Walsh","industry":"EDP Services","active":true,"website":"https://senate.gov","telephone":"670-875-9817","slogan":"Synergistic tertiary service-desk","address":"3 Sage Terrace","city":"Pont-Rouge","country":"Canada"},
{"id":49,"name":"Ullrich Inc","industry":"n/a","active":false,"website":"http://posterous.com","telephone":"179-150-7800","slogan":"Right-sized fresh-thinking migration","address":"1 Shasta Place","city":"Pleasant Point","country":"New Zealand"},
{"id":50,"name":"Von, Osinski and Stiedemann","industry":"Investment Managers","active":false,"website":"http://icq.com","telephone":"225-995-6141","slogan":"Cloned multi-tasking algorithm","address":"2 Calypso Circle","city":"Wolfville","country":"Canada"},
{"id":51,"name":"Metz, Pfannerstill and Wehner","industry":"Real Estate Investment Trusts","active":false,"website":"https://liveinternet.ru","telephone":"259-581-3088","slogan":"Polarised discrete interface","address":"03855 Hintze Pass","city":"Carman","country":"Canada"},
{"id":52,"name":"Hammes Group","industry":"n/a","active":false,"website":"http://princeton.edu","telephone":"317-807-9486","slogan":"Pre-emptive actuating groupware","address":"7376 Muir Road","city":"Seminole","country":"United States"},
{"id":53,"name":"Metz Group","industry":"Computer Communications Equipment","active":false,"website":"https://hugedomains.com","telephone":"860-252-0758","slogan":"Organized full-range moratorium","address":"63408 Gale Alley","city":"Hartford","country":"United States"},
{"id":54,"name":"Rodriguez, Lebsack and Gutkowski","industry":"Radio And Television Broadcasting And Communications Equipment","active":true,"website":"https://bloglovin.com","telephone":"406-546-8960","slogan":"Persistent local intranet","address":"47 Glendale Point","city":"Pierreville","country":"Canada"},
{"id":55,"name":"Bogan Inc","industry":"Business Services","active":false,"website":"http://xrea.com","telephone":"469-784-7011","slogan":"Visionary context-sensitive definition","address":"35 Ramsey Terrace","city":"Anmore","country":"Canada"},
{"id":56,"name":"Collier, Ziemann and Smitham","industry":"Office Equipment/Supplies/Services","active":true,"website":"http://ucoz.com","telephone":"475-540-9996","slogan":"Cross-platform high-level circuit","address":"703 Roxbury Junction","city":"Forestville","country":"Canada"},
{"id":57,"name":"Cole, Becker and Schiller","industry":"Biotechnology: Biological Products (No Diagnostic Substances)","active":false,"website":"http://cargocollective.com","telephone":"814-157-5995","slogan":"Virtual mobile pricing structure","address":"83 Bultman Center","city":"Little Current","country":"Canada"},
{"id":58,"name":"Heidenreich Group","industry":"n/a","active":false,"website":"http://state.gov","telephone":"615-361-5459","slogan":"User-centric zero defect migration","address":"79677 Shoshone Junction","city":"Nashville","country":"United States"},
{"id":59,"name":"Schuster-Turner","industry":"Other Consumer Services","active":false,"website":"http://intel.com","telephone":"922-943-7768","slogan":"Open-architected exuding knowledge user","address":"3731 Moose Point","city":"Oakville","country":"Canada"},
{"id":60,"name":"Wunsch-Schimmel","industry":"Real Estate","active":false,"website":"https://mayoclinic.com","telephone":"979-937-2645","slogan":"Up-sized static encoding","address":"790 Pleasure Point","city":"Bryan","country":"United States"},
{"id":61,"name":"Nicolas, Zemlak and Schaefer","industry":"Marine Transportation","active":false,"website":"http://163.com","telephone":"560-846-9524","slogan":"Reduced well-modulated hardware","address":"903 Sutherland Lane","city":"Sheffield","country":"United Kingdom"},
{"id":62,"name":"Wolf-Orn","industry":"n/a","active":true,"website":"http://hugedomains.com","telephone":"719-881-1294","slogan":"Total solution-oriented moderator","address":"32 Mandrake Junction","city":"Pueblo","country":"United States"},
{"id":63,"name":"Kessler, Bins and Yundt","industry":"Major Pharmaceuticals","active":true,"website":"https://fastcompany.com","telephone":"801-358-4475","slogan":"Persistent dedicated array","address":"2391 Union Court","city":"Salt Lake City","country":"United States"},
{"id":64,"name":"Hills-Nolan","industry":"Real Estate Investment Trusts","active":false,"website":"https://bbc.co.uk","telephone":"339-188-1693","slogan":"Customer-focused fresh-thinking definition","address":"9 Maryland Circle","city":"Port Colborne","country":"Canada"},
{"id":65,"name":"Abshire-O'Keefe","industry":"Investment Bankers/Brokers/Service","active":true,"website":"http://cpanel.net","telephone":"504-276-9009","slogan":"Self-enabling dynamic knowledge base","address":"70 Brentwood Terrace","city":"New Orleans","country":"United States"},
{"id":66,"name":"Stokes, Harber and Howe","industry":"Air Freight/Delivery Services","active":false,"website":"https://wordpress.com","telephone":"214-301-1432","slogan":"Multi-channelled multi-tasking instruction set","address":"908 Mallard Junction","city":"Mesquite","country":"United States"},
{"id":67,"name":"Hilll Group","industry":"Commercial Banks","active":true,"website":"https://slideshare.net","telephone":"965-854-3660","slogan":"Reduced methodical intranet","address":"7912 Crest Line Park","city":"Edinburgh","country":"United Kingdom"},
{"id":68,"name":"Kuhlman-Huel","industry":"Major Pharmaceuticals","active":true,"website":"https://dailymail.co.uk","telephone":"203-311-7880","slogan":"Inverse leading edge parallelism","address":"937 Independence Junction","city":"Waterbury","country":"United States"},
{"id":69,"name":"Bahringer-Emmerich","industry":"Integrated oil Companies","active":false,"website":"https://wikimedia.org","telephone":"239-920-6390","slogan":"Profound system-worthy Graphic Interface","address":"4478 Anzinger Road","city":"Fort Myers","country":"United States"},
{"id":70,"name":"Marvin Inc","industry":"Major Banks","active":true,"website":"http://free.fr","telephone":"277-545-8582","slogan":"Enhanced analyzing internet solution","address":"59 Dunning Drive","city":"Saskatoon","country":"Canada"},
{"id":71,"name":"Armstrong, Dooley and Hudson","industry":"Restaurants","active":false,"website":"http://webmd.com","telephone":"110-709-1242","slogan":"Right-sized cohesive website","address":"1 Brickson Park Parkway","city":"Neepawa","country":"Canada"}]
