=== npdev/backend-js-coding-test-main/data/schemas/employees.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "email": {
          "type": ["string", "null"],
          "format": "email"
        },
        "role": {
          "type": "string"
        },
        "company_id": {
          "type": ["integer", "null"]
        }
      },
      "required": ["id", "first_name", "last_name", "role"],
      "additionalProperties": false
    }
  }

=== npdev/backend-js-coding-test-main/data/employees/827ccb0eea8a706c4c34a16891f84e7b.json
[{"id":100,"first_name":"Jereme","last_name":"Brigstock","email":"jbrigstock2r@pinterest.com","role":"Research Associate","company_id":70},
{"id":101,"first_name":"Arlen","last_name":"Ragdale","email":"aragdale2s@sohu.com","role":"Senior Quality Engineer","company_id":29},
{"id":102,"first_name":"Redd","last_name":"Philipard","email":"rphilipard2t@ucsd.edu","role":"Executive Secretary","company_id":91},
{"id":103,"first_name":"Gavin","last_name":"Peagrim","email":"gpeagrim2u@wikispaces.com","role":"Marketing Manager","company_id":29},
{"id":104,"first_name":"Amabel","last_name":"Ramsey","email":"aramsey2v@nature.com","role":"Administrative Assistant II","company_id":52},
{"id":105,"first_name":"Deloris","last_name":"Jinda","email":"djinda2w@amazonaws.com","role":"Database Administrator I","company_id":9},
{"id":106,"first_name":"Elsey","last_name":"Samter","email":"esamter2x@netvibes.com","role":"Senior Editor","company_id":48},
{"id":107,"first_name":"Dorthea","last_name":"Tathacott","email":"dtathacott2y@paginegialle.it","role":"Software Engineer I","company_id":73},
{"id":108,"first_name":"Ronni","last_name":"Jarad","email":"rjarad2z@friendfeed.com","role":"Community Outreach Specialist","company_id":13},
{"id":109,"first_name":"Gerry","last_name":"Chidlow","email":"gchidlow30@wisc.edu","role":"Tax Accountant","company_id":37},
{"id":110,"first_name":"Glory","last_name":"Jorck","email":"gjorck31@accuweather.com","role":"Environmental Tech","company_id":50},
{"id":111,"first_name":"Bald","last_name":"Pepperd","email":"bpepperd32@jiathis.com","role":null,"company_id":9},
{"id":112,"first_name":"Colas","last_name":"Jessop","email":"cjessop33@ebay.com","role":"Payment Adjustment Coordinator","company_id":7},
{"id":113,"first_name":"Amalea","last_name":"Bowling","email":"abowling34@comcast.net","role":"Senior Developer","company_id":48},
{"id":114,"first_name":"Melany","last_name":"Berrane","email":"mberrane35@techcrunch.com","role":"Human Resources Assistant IV","company_id":66},
{"id":115,"first_name":"Fannie","last_name":"Mulderrig","email":"fmulderrig36@cyberchimps.com","role":"Dental Hygienist","company_id":91},
{"id":116,"first_name":"Willy","last_name":"Adamson","email":"wadamson37@about.me","role":"Environmental Specialist","company_id":69},
{"id":117,"first_name":"Brenda","last_name":"Parsall","email":"bparsall38@wisc.edu","role":null,"company_id":28},
{"id":118,"first_name":"Maible","last_name":"Trematick","email":null,"role":"Staff Scientist","company_id":82},
{"id":119,"first_name":"Layla","last_name":"Cordova","email":"lcordova3a@naver.com","role":"Statistician II","company_id":41},
{"id":120,"first_name":"Broddy","last_name":"Kalinsky","email":"bkalinsky3b@google.es","role":"Data Coordinator","company_id":29},
{"id":121,"first_name":"Merline","last_name":"Ettles","email":"mettles3c@pcworld.com","role":"Database Administrator IV","company_id":96},
{"id":122,"first_name":"Abbie","last_name":"Shapter","email":"ashapter3d@nymag.com","role":"Desktop Support Technician","company_id":17},
{"id":123,"first_name":"Gunar","last_name":"Aubrey","email":"gaubrey3e@tmall.com","role":"Software Engineer IV","company_id":8},
{"id":124,"first_name":"Berthe","last_name":"Risso","email":"brisso3f@nifty.com","role":"Health Coach III","company_id":89},
{"id":125,"first_name":"Gloriana","last_name":"Pretti","email":"gpretti3g@netlog.com","role":"Electrical Engineer","company_id":null},
{"id":126,"first_name":"Debby","last_name":"Haistwell","email":"dhaistwell3h@marriott.com","role":"Desktop Support Technician","company_id":97}]

=== npdev/backend-js-coding-test-main/data/employees/fcea920f7412b5da7be0cf42b8c93759.json
[{"id":187,"first_name":"Zak","last_name":"Cloughton","email":"zcloughton56@myspace.com","role":"Senior Sales Associate","company_id":69},
{"id":188,"first_name":"Timofei","last_name":"Pietraszek","email":"tpietraszek57@infoseek.co.jp","role":"Health Coach I","company_id":39},
{"id":189,"first_name":"Erin","last_name":"Picknett","email":"epicknett58@sphinn.com","role":"Editor","company_id":54},
{"id":190,"first_name":"Murdoch","last_name":"Dicey","email":"mdicey59@dailymotion.com","role":"Design Engineer","company_id":38},
{"id":191,"first_name":"Vanny","last_name":"Kliement","email":"vkliement5a@answers.com","role":"Food Chemist","company_id":47},
{"id":192,"first_name":"Francklin","last_name":"Lobb","email":"flobb5b@pbs.org","role":"Project Manager","company_id":93},
{"id":193,"first_name":"Brittani","last_name":"Chezier","email":"bchezier5c@weibo.com","role":"Chemical Engineer","company_id":48},
{"id":194,"first_name":"Leeanne","last_name":"Tome","email":"ltome5d@parallels.com","role":"Actuary","company_id":39},
{"id":195,"first_name":"Chad","last_name":"Lynock","email":"clynock5e@biglobe.ne.jp","role":"Civil Engineer","company_id":67},
{"id":196,"first_name":"Jackson","last_name":"Hardern","email":"jhardern5f@xrea.com","role":"GIS Technical Architect","company_id":23},
{"id":197,"first_name":"Lindy","last_name":"Headrick","email":"lheadrick5g@princeton.edu","role":"Structural Engineer","company_id":82},
{"id":198,"first_name":"Aprilette","last_name":"Minthorpe","email":"aminthorpe5h@hostgator.com","role":"Actuary","company_id":44},
{"id":199,"first_name":"Isobel","last_name":"Lamasna","email":"ilamasna5i@gnu.org","role":"Research Associate","company_id":45},
{"id":200,"first_name":"Karry","last_name":"Balthasar","email":"kbalthasar5j@flavors.me","role":"Geologist I","company_id":69}]

=== npdev/backend-js-coding-test-main/data/employees/25f9e794323b453885f5181f1b624d0b.json
[{"id":28,"first_name":"Izzy","last_name":"Moorhouse","email":"imoorhouser@sphinn.com","role":"Geologist IV","company_id":23},
{"id":29,"first_name":"Janice","last_name":"Maultby","email":"jmaultbys@google.com","role":"Structural Engineer","company_id":33},
{"id":30,"first_name":"Harwell","last_name":"Gurnell","email":"hgurnellt@nbcnews.com","role":"Payment Adjustment Coordinator","company_id":null},
{"id":31,"first_name":"Merrel","last_name":"De Lorenzo","email":"mdelorenzou@prnewswire.com","role":"Assistant Media Planner","company_id":25},
{"id":32,"first_name":"Shurwood","last_name":"Emmens","email":"semmensv@jugem.jp","role":"General Manager","company_id":92},
{"id":33,"first_name":"Agosto","last_name":"Gilstin","email":"agilstinw@skyrock.com","role":"Speech Pathologist","company_id":51},
{"id":34,"first_name":"Cherida","last_name":"Petran","email":"cpetranx@bigcartel.com","role":"Quality Control Specialist","company_id":27},
{"id":35,"first_name":"Barny","last_name":"Orpyne","email":null,"role":"Human Resources Manager","company_id":null},
{"id":36,"first_name":"Dewitt","last_name":"Richmont","email":"drichmontz@cisco.com","role":"Editor","company_id":16},
{"id":37,"first_name":"Berk","last_name":"Roark","email":"broark10@shop-pro.jp","role":"Chief Design Engineer","company_id":49},
{"id":38,"first_name":"Kristal","last_name":"Alessandrelli","email":"kalessandrelli11@photobucket.com","role":"Accounting Assistant I","company_id":100}]

=== npdev/backend-js-coding-test-main/data/employees/202cb962ac59075b964b07152d234b70.json
[{"id":81,"first_name":"Marsh","last_name":"Bedell","email":"mbedell28@theguardian.com","role":"Financial Analyst","company_id":97},
{"id":82,"first_name":"Odelia","last_name":"Lodewick","email":"olodewick29@whitehouse.gov","role":"Associate Professor","company_id":12},
{"id":83,"first_name":"Marys","last_name":"Hatrey","email":"mhatrey2a@cam.ac.uk","role":"Nurse","company_id":45},
{"id":84,"first_name":"Evey","last_name":"Lower","email":"elower2b@multiply.com","role":"Librarian","company_id":null},
{"id":85,"first_name":"Chadd","last_name":"Faucett","email":"cfaucett2c@youtu.be","role":"VP Product Management","company_id":62},
{"id":86,"first_name":"Meggy","last_name":"Barth","email":"mbarth2d@examiner.com","role":"Human Resources Assistant II","company_id":32},
{"id":87,"first_name":"Bernice","last_name":"Tows","email":"btows2e@amazon.de","role":"Geologist II","company_id":35},
{"id":88,"first_name":"Ches","last_name":"Pristnor","email":"cpristnor2f@shinystat.com","role":"Senior Cost Accountant","company_id":8},
{"id":89,"first_name":"Mona","last_name":"O'Glessane","email":"moglessane2g@trellian.com","role":"Help Desk Operator","company_id":68},
{"id":90,"first_name":"Eudora","last_name":"Kollatsch","email":"ekollatsch2h@php.net","role":"Office Assistant IV","company_id":40},
{"id":91,"first_name":"Kelcy","last_name":"Marling","email":null,"role":"Community Outreach Specialist","company_id":21},
{"id":92,"first_name":"Aubrie","last_name":"Bourdas","email":"abourdas2j@blogs.com","role":"Physical Therapy Assistant","company_id":52},
{"id":93,"first_name":"Wilone","last_name":"Wadeson","email":"wwadeson2k@cbc.ca","role":"Help Desk Technician","company_id":2},
{"id":94,"first_name":"Gabey","last_name":"Hawkett","email":"ghawkett2l@altervista.org","role":"Senior Cost Accountant","company_id":null},
{"id":95,"first_name":"Frederick","last_name":"Housby","email":"fhousby2m@census.gov","role":"Help Desk Technician","company_id":71},
{"id":96,"first_name":"Gran","last_name":"Banat","email":"gbanat2n@angelfire.com","role":"Assistant Media Planner","company_id":69},
{"id":97,"first_name":"Waylin","last_name":"Meneux","email":"wmeneux2o@cloudflare.com","role":"Developer III","company_id":36},
{"id":98,"first_name":"Nickie","last_name":"Le feaver","email":"nlefeaver2p@cam.ac.uk","role":"Financial Analyst","company_id":66},
{"id":99,"first_name":"Tabbie","last_name":"Jerrolt","email":"tjerrolt2q@4shared.com","role":"Research Assistant I","company_id":56}]

=== npdev/backend-js-coding-test-main/data/employees/e807f1fcf82d132f9bb018ca6738a19f.json
[{"id":164,"first_name":"Celeste","last_name":"Bulteel","email":"cbulteel4j@dell.com","role":"Sales Representative","company_id":70},
{"id":165,"first_name":"Veronique","last_name":"Sidnall","email":"vsidnall4k@businessinsider.com","role":"Nuclear Power Engineer","company_id":56},
{"id":166,"first_name":"Auria","last_name":"Boram","email":"aboram4l@sogou.com","role":"Senior Sales Associate","company_id":94},
{"id":167,"first_name":"Fayre","last_name":"Giddings","email":"fgiddings4m@51.la","role":"Office Assistant II","company_id":89},
{"id":168,"first_name":"Reynold","last_name":"Yanyushkin","email":"ryanyushkin4n@home.pl","role":"Web Designer I","company_id":30},
{"id":169,"first_name":"Vale","last_name":"Hayton","email":"vhayton4o@seesaa.net","role":"Operator","company_id":96},
{"id":170,"first_name":"Lynette","last_name":"Riddington","email":"lriddington4p@oakley.com","role":"Human Resources Assistant III","company_id":65},
{"id":171,"first_name":"Gifford","last_name":"Hellwig","email":null,"role":null,"company_id":99},
{"id":172,"first_name":"Joletta","last_name":"Mecozzi","email":null,"role":"Information Systems Manager","company_id":35},
{"id":173,"first_name":"Nola","last_name":"Domange","email":"ndomange4s@youtube.com","role":"Administrative Assistant IV","company_id":74},
{"id":174,"first_name":"Sawyer","last_name":"Ruffli","email":"sruffli4t@unicef.org","role":"Analog Circuit Design manager","company_id":58},
{"id":175,"first_name":"Philip","last_name":"Slott","email":null,"role":"Staff Scientist","company_id":92},
{"id":176,"first_name":"Randa","last_name":"Callister","email":"rcallister4v@howstuffworks.com","role":"Senior Sales Associate","company_id":11},
{"id":177,"first_name":"Abagael","last_name":"Cuthbertson","email":"acuthbertson4w@tinyurl.com","role":"Software Engineer II","company_id":94},
{"id":178,"first_name":"Betteanne","last_name":"Brocklehurst","email":"bbrocklehurst4x@jimdo.com","role":"Financial Analyst","company_id":52},
{"id":179,"first_name":"Mendie","last_name":"Jirusek","email":"mjirusek4y@weebly.com","role":"Editor","company_id":94},
{"id":180,"first_name":"Leanna","last_name":"Brane","email":"lbrane4z@google.pl","role":"Human Resources Assistant III","company_id":44},
{"id":181,"first_name":"Corey","last_name":"Cremer","email":"ccremer50@dailymotion.com","role":"Systems Administrator III","company_id":70},
{"id":182,"first_name":"Zandra","last_name":"Juett","email":"zjuett51@uiuc.edu","role":"Data Coordinator","company_id":33},
{"id":183,"first_name":"Dyann","last_name":"O'Dwyer","email":"dodwyer52@umich.edu","role":"Analyst Programmer","company_id":62},
{"id":184,"first_name":"Maure","last_name":"Masden","email":"mmasden53@studiopress.com","role":"Librarian","company_id":26},
{"id":185,"first_name":"Aimee","last_name":"Glynne","email":"aglynne54@washingtonpost.com","role":"Cost Accountant","company_id":51},
{"id":186,"first_name":"Ruperta","last_name":"Walkingshaw","email":"rwalkingshaw55@ucsd.edu","role":"Senior Quality Engineer","company_id":53}]

=== npdev/backend-js-coding-test-main/data/employees/c4ca4238a0b923820dcc509a6f75849b.json
[{"id":127,"first_name":"Earlie","last_name":"Eccersley","email":"eeccersley3i@cbsnews.com","role":"Assistant Media Planner","company_id":54},
{"id":128,"first_name":"Adrien","last_name":"Weedon","email":"aweedon3j@skype.com","role":"Nurse","company_id":39},
{"id":129,"first_name":"Ramsay","last_name":"Mitroshinov","email":"rmitroshinov3k@yandex.ru","role":"Design Engineer","company_id":null}]

=== npdev/backend-js-coding-test-main/__tests__/test_data/employees.json
[{"id":9,"first_name":"Gustav","last_name":"Seiler","email":"gseiler8@alibaba.com","role":"Human Resources Manager","company_id":25},
{"id":10,"first_name":"Dar","last_name":"Killingworth","email":null,"role":"VP Product Management","company_id":25},
{"id":11,"first_name":"Caroljean","last_name":"Cancellario","email":"ccancellarioa@fastcompany.com","role":"Chemical Engineer","company_id":26}]
